### ISSUE TITLE
Argument order of BlockchainStorageInfo constructor is shifted

### ISSUE THREAD

**Issue by planethouki** [nemtech/nem2-sdk-typescript-javascript#29] opened 2018-11-24 09:11 UTC
## 1. Expected behavior and actual behavior.

BlockchainStorageInfo obtained by blockchainHttp.getDiagnosticStorage() has invalid key-value pair.

`numAccounts` shows number of blocks
`numBlocks` shows number of transactions
`numTransactions` shows number of accounts

### Expected behavior

```javascript
BlockchainStorageInfo { 
	numBlocks: 89263, 
	numTransactions: 444, 
	numAccounts: 81 
}
```

### Actual behavior

```javascript
BlockchainStorageInfo { 
	numAccounts: 89263, 
	numBlocks: 444, 
	numTransactions: 81 
}
```

To compare, rest api of `/diagnostic/storage` returns
```json
{
	"numBlocks": 89263,
	"numTransactions": 444,
	"numAccounts": 81
}
```

## 2. Steps to reproduce the problem.

Run this code.

```javascript
const nem2Sdk = require("nem2-sdk");
const BlockchainHttp = nem2Sdk.BlockchainHttp;
const host = <something host>;
const blockchainHttp = new BlockchainHttp(host);
blockchainHttp.getDiagnosticStorage().subscribe(
    x => console.log(x)
);
```

## 3. Specifications like the version of the project, operating system, or hardware.

node: v10.11.0
nem2-sdk: 0.10.1
rest-gateway is docker image: techbureau/catapult-rest-server:1.0.7
catapult node is docker image: techbureau/catapult-server:gcc-0.1.0.2

## 4. More information

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/model/blockchain/BlockchainStorageInfo.ts
```javascript
constructor(
	public readonly numAccounts: number,
	public readonly numBlocks: number,
	public readonly numTransactions: number) {
}
```

is should be

```javascript
constructor(
	public readonly numBlocks: number,
	public readonly numTransactions: number,
	public readonly numAccounts: number) {
}
```

and also test

https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/test/model/blockchain/BlockchainStorageInfo.spec.ts

**Comment by evias** [comment] 2019-02-12 05:44
Since the wrong parameters order was only defined in the *model* constructor and everywhere else several calls to the BlockchainStorageInfo class would imply the aforementioned `Expected Behaviour`, it seemed like an important fix to make.

The unit test has been updated to reflect the newly ordered parameters.

Thanks @planethouki !

**Comment by evias** [comment] 2019-02-21 16:35
merged fix

**Closed by evias** 2019-02-21 16:35 UTC
Labels: bug
