### ISSUE TITLE
Wrong cosigner when converting account to multisig account

### ISSUE THREAD

**Issue by kahwooi** [nemtech/nem2-sdk-typescript-javascript#245] opened 2019-09-06 08:28 UTC
I am following this [https://nemtech.github.io/guides/account/converting-an-account-to-multisig.html](https://nemtech.github.io/guides/account/converting-an-account-to-multisig.html) to convert an account to a multisig account. 

The transaction is announce successfully, but the wired part is at the  `Cosign the AggregateTransaction `.

I am expecting Alice and Bob to consign the aggregate transaction, but non of them receive the `aggregateBondedTransactions`. 

When I try to use the multisig account to consign it, and it did go through successfully. I am confuse.

This is how I cosign the aggregate transaction, and using multisig account went through:

```
accountHttp
    .aggregateBondedTransactions(multisigAccount.publicAccount, new QueryParams(100))
    .pipe(
        mergeMap((_) => _),
        filter((_) => _.transactionInfo !== undefined && _.transactionInfo.hash !== undefined &&
            _.transactionInfo.hash === hash), // Filter transaction
        toArray(),
    )
    .subscribe((transactions: AggregateTransaction[]) => {
        console.log(transactions.length)
        if (transactions.length) {
            const transaction = transactions[0];
            const cosignatureTransaction = CosignatureTransaction.create(transaction);
            const signedCosignature = multisigAccount.signCosignatureTransaction(cosignatureTransaction);

            transactionHttp.announceAggregateBondedCosignature(signedCosignature).subscribe(
                () => {
                    console.log('Transaction cosigned and announced correctly');
                }, (err) => {
                    console.log(err.response !== undefined ? err.response.text : err);
                });

        }
    });
```
I am using below:
"nem2-sdk": "^0.13.1"
"catapult-server":"v0.5.0.1"

-----------------------
Related issue:

After signed by multisig account, I try to `getMultisigAccountInfo`:
```
accountHttp
.getMultisigAccountInfo(address)
.subscribe(accountInfo => console.log(accountInfo), err => console.error(err));
```
I get an error and undefined result:

` body: MultisigAccountInfoDTO { multisig: undefined } }`

**Comment by dgarcia360** [comment] 2019-09-06 16:04
Hi @kahwooi thanks for reporting t

**Comment by dgarcia360** [comment] 2019-09-06 16:12
Hi @kahwooi,

As you have remarked, Alice and Bob need to opt-in in order to create the multisig account. We need to figure out why you are not receiving the aggregate bonded transaction. Could you paste here the complete code you are using to create the multisig account? 

Although you are able to announce a cosignature from the multisig account, this cosignature should not have any effect as Alice and Bob still need to cosign the transaction.

**Comment by kahwooi** [comment] 2019-09-07 00:22
This is how I announce it:
```
import { TransactionHttp, Listener, Account, NetworkType, PublicAccount, 
    ModifyMultisigAccountTransaction, Deadline, MultisigCosignatoryModification, MultisigCosignatoryModificationType, AggregateTransaction, HashLockTransaction, NetworkCurrencyMosaic, UInt64 } from "nem2-sdk";
import { filter, mergeMap } from 'rxjs/operators' 

const nodeUrl = 'http://localhost:3000'
const transactionHttp = new TransactionHttp(nodeUrl)
const listener = new Listener(nodeUrl)

//multisig
const accountPrivateKey = '636DD04F4C88C7B6...';
const multisigAccount = Account.createFromPrivateKey(accountPrivateKey , NetworkType.MIJIN_TEST);
//alice_grada
const alicePublicKey = 'D083746AB1335495CDE4A1...'
const cosignatory1 = PublicAccount.createFromPublicKey(alicePublicKey, NetworkType.MIJIN_TEST);
//bob_grada
const bobPublicKey = '1F4C94B5B622C003117...'
const cosignatory2 = PublicAccount.createFromPublicKey(bobPublicKey, NetworkType.MIJIN_TEST);

//MultisigAccountModificationTransaction
const convertIntoMultisigTransaction = ModifyMultisigAccountTransaction.create(
    Deadline.create(),
    1,
    1,
    [
        new MultisigCosignatoryModification(
            MultisigCosignatoryModificationType.Add,
            cosignatory1,
        ),
        new MultisigCosignatoryModification(
            MultisigCosignatoryModificationType.Add,
            cosignatory2,
        )],
    NetworkType.MIJIN_TEST)

//AggregateBondedTransaction
const aggregateTransaction = AggregateTransaction.createBonded(
    Deadline.create(),
    [convertIntoMultisigTransaction.toAggregate(multisigAccount.publicAccount)],
    NetworkType.MIJIN_TEST)

//Sign tx with the multisig account
const networkGenerationHash = '8505335DDE38967F78400FEA3FFB75...';
const signedTransaction = multisigAccount.sign(aggregateTransaction, networkGenerationHash);
console.log(signedTransaction.hash);

//app_provider
const appProviderPrivateKey = 'BED47F18F7EBDDF773444967E441....';
const appProviderAccount = Account.createFromPrivateKey(appProviderPrivateKey, NetworkType.MIJIN_TEST);

//lock 10 cat.currancy using app_provider account
const hashLockTransaction = HashLockTransaction.create(
    Deadline.create(),
    NetworkCurrencyMosaic.createRelative(10),
    UInt64.fromUint(480),
    signedTransaction,
    NetworkType.MIJIN_TEST)
const hashLockTransactionSigned = appProviderAccount.sign(hashLockTransaction, networkGenerationHash);

listener.open().then(() => {

    //annouce hash lock transaction
    transactionHttp
        .announce(hashLockTransactionSigned)
        .subscribe(x => console.log(x), err => console.error(err));

    //confirm hash lock transaction, then annouce AggregateTransaction 
    listener
        .confirmed(appProviderAccount.address)
        .pipe(
            filter((transaction) => transaction.transactionInfo !== undefined
                && transaction.transactionInfo.hash === hashLockTransactionSigned.hash),
            mergeMap(ignored => transactionHttp.announceAggregateBonded(signedTransaction))
        )
        .subscribe(announcedAggregateBonded => console.log(announcedAggregateBonded),
            err => console.error(err));
})
```

**Comment by evias** [comment] 2019-09-07 18:40
after review of the code, it seems _correct_. I am not sure about the `appProviderAccount` which signs the `HashLockTransaction` as this account is not linked in the loop otherwise. Maybe a cosignatory must sign the hashlock? @dgarcia360 can someone else pay for the hashlock ? Knowing the hashlock is linked to the SignedTransaction, it is possible, but would want to confirm.

But I would think that Alice and Bob not being notified is still a bug because if the aggregate bonded transaction gets announced, as david points out they must opt-in to the multi-signature config.

**Comment by kahwooi** [comment] 2019-09-08 04:43
I have gone through my code above many time, tested many times, `Alice `and `Bob `account din't receive any aggregate bonded notification, but `Multisig `account receive it. I don't know what has gone wrong. What are the things I can look at, e.g config or some other code example?

**Comment by dgarcia360** [comment] 2019-09-08 11:37
Hi @kahwooi, thanks for sharing the complete code! After running the example several times, I didn't manage either to get the aggregated bonded transaction modification from the cosignatory account. Core devs are informed, it will be necessary to make Alice and Bob receivers of the notification as well to make this feature more usable.

In the meanwhile, we will update the docs with a workaround. You can still opt-in the transaction with Alice and Bob profiles. How? Querying the transaction from the future multisig account partial channel. Here you have a code snippet yu can use to opt-in ModifyMultisigModificationTransactions https://gist.github.com/dgarcia360/32c97c99c4c18e801421d352feba2ce6 

For the use case, you will have to run the snippet twice: one setting Alice's account as the ``cosignatoryPrivateKey`` and a second one with Bob's account.

@evias ``can someone else pay for the hashlock ?`` Yes, this is possible. The code looks correct, it's a docs + feature behaviour problem.

**Comment by rg911** [comment] 2019-09-11 20:51
@Wayonb

**Comment by kahwooi** [comment] 2019-09-12 06:51
@dgarcia360, is there a way to listen and return a list of cosigners that require to approve the transaction, because currently I have to create multiple listener for each cosigner: 

```
listener.open().then(() => {
    listener
        .aggregateBondedAdded(cosignatory1.address) // alice
     .....
    listener
        .aggregateBondedAdded(cosignatory2.address) // bob
```

**Comment by kahwooi** [comment] 2019-09-17 06:36
Why I cannot get the aggregateBondedTransactions, after transaction is successfully anounce using announceAggregateBonded:

```
listener.open().then(() => {

    //annouce hash lock transaction
    transactionHttp
        .announce(hashLockTransactionSigned)
        .subscribe(x => console.log(x), err => console.error(err));

    //confirm hash lock transaction, then annouce AggregateTransaction 
    listener
        .confirmed(appProviderAccount.address)
        .pipe(
            filter((transaction) => transaction.transactionInfo !== undefined
                && transaction.transactionInfo.hash === hashLockTransactionSigned.hash),
            mergeMap(ignored => transactionHttp.announceAggregateBonded(signedTransaction))
        )
        .subscribe(announcedAggregateBonded => {
            console.log(announcedAggregateBonded);
            accountHttp.aggregateBondedTransactions(multisigAccount.publicAccount,  new QueryParams(100))
            .pipe(
                mergeMap((_) => _),
                filter((transaction) => transaction.transactionInfo !== undefined
                    && transaction.transactionInfo.hash === signedTransaction.hash),
                map(transaction => console.log(transaction)) // Nothing here?
            )
        },
            err => console.error(err));
})
```

**Comment by jorisadri** [comment] 2019-09-24 06:35
Any update on this issue?

**Comment by dgarcia360** [comment] 2019-09-24 07:08
@jorisadri Next Catapult release should notify as well the cosignatories.

**Comment by rg911** [comment] 2019-09-24 08:03
I was going to ask the same question, Thanks @dgarcia360 . but do we have any insight of what's going on with this issue, and what changes potentially are needed?

**Comment by dgarcia360** [comment] 2019-09-24 09:29
If an account is added as a potential multisig account cosignatory, this will receive a notification through the ``aggregatebonded`` channel to opt-in.  Theoretically, we don't need to change anything in the SDK/REST level.

**Comment by yaaccount** [comment] 2019-09-24 13:27
Hi! ... was just digging into the same issue. It seems the message already is on the aggregateBonded channel for the cosignatory, but is filtered-out. See this: https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/7952d248fe330118e8fed037f94e3eb1554e602b/src/infrastructure/Listener.ts#L409 ... the method is a) not used, b) wrongly implemented (return true does nothing, it is not propagated out of the map).

It could be used here as && in the condition: https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/7952d248fe330118e8fed037f94e3eb1554e602b/src/infrastructure/Listener.ts#L374

... then it seems to work for me. (again, this is against xpx server, might not be relevant for nem)

**Comment by rg911** [comment] 2019-09-24 14:13
`accountAddedToMultiSig` was never used as previously confirmed by core that we don't have this channel

**Comment by yaaccount** [comment] 2019-09-24 14:19
> `accountAddedToMultiSig` was never used as previously confirmed by core that we don't have this channel

Yes, what I say is that the message is already present on the `partialAdded` channel, but filtered out, since it is not `transactionHasSignerOrReceptor` ... but it could be fullfill the `accountAddedToMultiSig` condition, as the implementation of that function suggests.

**Comment by rg911** [comment] 2019-09-26 19:48
@yaaccount there's a fix merged to master but not released yet. Will be included shortly in the RC release, but feel free to give it try

**Comment by dgarcia360** [comment] 2019-10-03 08:53
The latest catapult-server release should fix this: https://github.com/nemtech/catapult-server/commit/8bf65946a710b6a89a2e6ac1534b61815b792b78
 
- Notify cosignatories' public keys in order to allow added cosignatories to get aggregate notifications.

**Comment by rg911** [comment] 2019-10-04 22:35
close this issue now??

**Closed** 2019-10-15 14:03 UTC
Labels: bug
